### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by Zoosterbaan** [23rd-gaming-division/OperationCrimsonSunrise.Panthera3#1]

**Comment by AJCStriker** [comment]
We should definitely use ALiVE for this because they have a pretty strong set for this.

We need to make sure that the operations server is setup with the ALiVE database otherwise it will fuck up.

Other than that we need to make sure that all of the operations share a PBO name, which might cause some issues with Git.

My suggestion is that we simply rename the final PBOs that we submit to the GitHub releases. Otherwise we have to use some complex multi branching setup.

The other thing is that we need to change the onLoad name in the description per the alive settings. Relevant information can be found at http://alivemod.com/wiki/index.php/ALiVE_Data under the resetting stats and persistence header.

**Comment by rasolercrespo** [comment]
Thinking ahead: how could the ops single death policy affect player persistence?

**Comment by AJCStriker** [comment]
@rasolercrespo that's an interesting question. I guess we have to rely on the ALiVE admin teleport tools to bring them back, or just let aviation / combat logistics work out a resupply of deceased personnel.

I don't think we should scrap the policy, but we need to work out the best way to get missions started quickly without sacrificing persistence.

**Comment by Oges03** [comment]
I like the reenforcement by support elements at the start of each for the dead guys

**Comment by rasolercrespo** [comment]
I have no effing clue, so I didn't even touch this.

**Comment by rasolercrespo** [comment]
Fuck knows now, @AJCStriker...
